version: "2.3"
services:
  mongo:
    image: mongo:3.6
    container_name: unifi-mongo-211
    restart: unless-stopped
    volumes:
      - /share/CACHEDEV1_DATA/Container/unifi/mongo/db:/data/db
      - /share/CACHEDEV1_DATA/Container/unifi/mongo/configdb:/data/configdb
    networks:
      - unifi

  controller:
    image: jacobalberty/unifi:latest
    container_name: unifi-controller-211
    mac_address: "02:42:55:08:f0:92"
    depends_on:
      - mongo
    init: true
    restart: unless-stopped
    environment:
      TZ: Europe/Berlin
      SYSTEM_IP: 192.168.188.211
      DB_URI: mongodb://mongo/unifi
      STATDB_URI: mongodb://mongo/unifi_stat
      DB_NAME: unifi
    volumes:
      - /share/CACHEDEV1_DATA/Container/unifi/controller:/unifi
    networks:
      qnet:
        ipv4_address: 192.168.188.211
      unifi:

networks:
  qnet:
    external: true
    name: qnet-static-eth1-5b3662
  unifi:
    driver: bridge
